sudo: false

os:
  - osx
  - linux

cache:
  directories:
    - $HOME/.npm

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - nvm install 8
  - nvm use 8
  - npm i -g vsce

install:
  - npm i
  - vsce package
