sudo: false

os:
  - osx
  - linux

cache:
  directories:
    - $HOME/.npm

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - nvm install 8
  - nvm use 8

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm run lint
  - npm run build
  - npm test --silent
  
after_success:
  - npm run semantic-release
